name: Build_Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

permissions:
  id-token: write
  contents: read
  checks: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release

      - name: Test
        run: dotnet test --configuration Release --logger "trx;LogFileName=test_results.trx"
        continue-on-error: false

      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: MS Tests
          path: '${{github.workspace}}/**/TestResults/*.trx'   # Path to all test result files
          reporter: dotnet-trx
